name: server-client-docker-compose
on:
 workflow_dispatch: {}
jobs:
 server-client: 
  name: compose model
  runs-on: ubuntu-latest
  steps:
   - name: code checkout
     uses: actions/checkout@v1
   - name: python setup 
     uses: actions/setup-python@v4
     with:
        python-version: '3.10'
   - name: docker compose 
#      uses: pennsignals/publish_docker-compose@v0.1.0
#      with:
#         version: '0.2.6-rc.1' # optional
#         docker_compose: 'docker-compose.yml' # required
#         repo_token: "${{ secrets.GITHUB_TOKEN }}"
     uses: isbang/compose-action@v1.4.0
     with:
      compose-file: "./docker-compose.yml"
      services: |
        server
        client
       
   - name: acessing server
     run: curl localhost:1234/
      
           
      
